name: build-image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Inject automatic version on config.xml
        run: |
          NEW_VERSION="0.0.${{ github.run_number }}"
          echo "New version: $NEW_VERSION"
          
          # Automatic replace
          sed -i "s|<version>.*</version>|<version>$NEW_VERSION</version>|g" config.xml
          
          # Save new version variable
          echo "IMAGE_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Debug environment
        run: |
          whoami
          id
          docker version

      - name: Ensure kiwi cache exists
        run: |
          sudo mkdir -p /var/cache/kiwi
          sudo chmod 777 /var/cache/kiwi

      - name: Pull kiwi image
        run: |
          sudo docker pull registry.opensuse.org/opensuse/bci/kiwi:latest


      - name: Build KIWI image with Docker
        run: |
          sudo docker run --rm --privileged \
            -v /dev:/dev \
            -v ${{ github.workspace }}:/workspace \
            -v /var/cache/kiwi:/var/cache/kiwi \
            --network host \
            registry.opensuse.org/opensuse/bci/kiwi:latest \
            kiwi-ng --loglevel 2 system build \
            --description /workspace \
            --target-dir /workspace/output

      - name: List output files
        run: |
          ls -lh output/

      - name: Crear Release Oficial y Adjuntar QCOW2
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.IMAGE_VERSION }}
          name: Release v${{ env.IMAGE_VERSION }}
          body: |
            ## Nueva versión de la imagen inmutable para Kubernetes
            
            Compilación automatizada en el Homelab.
            - **Versión base:** openSUSE Leap Micro 6.2
            - **Build ID:** ${{ github.run_id }}
            - **Commit:** ${{ github.sha }}
          draft: false
          prerelease: false
          # Apuntamos directamente al archivo de disco virtual final
          files: output/*.qcow2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: openSUSE-Leap-Micro-6.2-custom.x86_64-${{ env.IMAGE_VERSION }}
#          path: output/*.qcow2
#          retention-days: 3

      - name: Post-Build clean
        if: always()
        run: |
          echo "Cleaning up"
          sudo rm -rf ./output